In [6]:
import pandas as pd
import numpy as np
#dir_envol = r'I:\Meganz\PMMG\MySql\10 - Tbl_dimensao\gdo\tbl_envolvidos.csv'#Home
#dir_envol = r'C:\Users\Geo\Documents\MEGAsync\MySql\10 - Tbl_dimensao\gdo\tbl_envolvidos.csv'#Office
#df_envol = pd.read_csv(dir_envol, sep=";", encoding='utf8', low_memory =False)


df_envol = pd.read_sql_table('tbl_envolvidos', 'sqlite:///gdo.db',
                       )

In [7]:
df_envol.columns

Index(['NREDS', 'ORG_UN_REG', 'UN_AREA_MIL', 'UN_REGISTRO', 'COD_DIAO', 'T_C',
       'COD_DELITO', 'T_C_DELITO', 'GRAU_LESAO', 'TIPO_ENVOLVIMENTO',
       'GRUPO_TIPO_ENVOL', 'PRISAO_APREES', 'DATA_FATO', 'HORA',
       'DATA_ULT_ATT', 'LOG_TIPO', 'LOGRADOURO', 'LOGRADOURO_NAO_CAD',
       'LOGRADOURO_CRUZ', 'LOGRADOURO_CRUZ_NAO_CAD', 'N_LOG', 'BAIRRO',
       'BAIRRO_NAO_CAD', 'COMPLEMENTO_END', 'PONTO_REF', 'MUNICIPIO',
       'LATITUDE', 'LONGITUDE', 'NOME_ENVOL', 'DATA_NASC', 'SEXO', 'CUTIS',
       'IDADE', 'ESTADO_CIVIL', 'OCUPACAO', 'ESCOLARIDADE', 'LOGRADOURO_ENVOL',
       'BAIRRO_ENVOL', 'TIPO_LOG_ENVOL', 'MUNICIPIO_ENVOL', 'QTDE_ENVOL',
       'SETOR', 'FRACAO', 'CIA', 'UEOP', 'HC', 'NPAA'],
      dtype='object')

In [10]:
df_envol['IDADE'].describe()

count    13034.000000
mean        33.799217
std         15.132068
min          0.000000
25%         22.000000
50%         31.000000
75%         43.000000
max         98.000000
Name: IDADE, dtype: float64

In [9]:
df_envol['IDADE'].min()

0.0

In [62]:
#df_envol[df_envol.'Estado Civil'== 'SOLTEIRO'.'Idade Aparente'].max() 
#notação por ponto  vale  quando o nome do campo  não tem espaço
df_envol[df_envol['Estado Civil']== 'SOLTEIRO']['Idade Aparente'].max()

87.0

In [72]:
df_envol.shape

(12244, 41)

In [77]:
#df_crimes.filter(like ='Cód.').head()

df_envol[df_envol['Estado Civil'].isin(['SOLTEIRO'])]['Idade Aparente'].max()

87.0

In [20]:
df_envol[['ESTADO_CIVIL','IDADE']].groupby(['ESTADO_CIVIL']).count()

                              IDADE
ESTADO_CIVIL
CASADO                         3151
DIVORCIADO                      287
ESTADO CIVIL - IGNORADO        2569
ESTADO CIVIL - NAO DECLARADO   1273
PREENCHIMENTO OPCIONAL           16
SEPARADO JUDICIALMENTE           83
SOLTEIRO                       4898
UNIAO ESTAVEL                   634
VIUVO                           123

In [115]:
df_envol[['Estado Civil', 'Escolaridade','Idade Aparente']].groupby(['Estado Civil', 'Escolaridade']).mean().round(1)

                                                                       Idade Aparente
Estado Civil            Escolaridade
CASADO                  ALFABETIZADO                                             45.8
                        ANALFABETO                                               52.1
                        ENSINO FUNDAMENTAL COMPLETO (8 ANOS ESTUDO)              43.0
                        ENSINO FUNDAMENTAL INCOMPLETO (8 ANOS ESTUDO)            48.2
                        ENSINO MEDIO COMPLETO (2º GRAU)                          40.4
                        ENSINO MEDIO INCOMPLETO ( 2º GRAU)                       37.9
                        ESCOLARIDADE - IGNORADA                                  45.0
                        OUTROS - ESCOLARIDADE                                    44.1
                        POS-GRADUACAO                                            44.3
                        SUPERIOR COMPLETO                                        40.7
                        SUPERIOR INCOMPLETO                                      37.2
DIVORCIADO              ALFABETIZADO                                             47.3
                        ANALFABETO                                               50.3
                        ENSINO FUNDAMENTAL COMPLETO (8 ANOS ESTUDO)              46.7
                        ENSINO FUNDAMENTAL INCOMPLETO (8 ANOS ESTUDO)            50.2
                        ENSINO MEDIO COMPLETO (2º GRAU)                          45.5
                        ENSINO MEDIO INCOMPLETO ( 2º GRAU)                       44.5
                        ESCOLARIDADE - IGNORADA                                  46.0
                        OUTROS - ESCOLARIDADE                                    37.6
                        POS-GRADUACAO                                            52.5
                        SUPERIOR COMPLETO                                        46.4
                        SUPERIOR INCOMPLETO                                      43.6
ESTADO CIVIL - IGNORADO ALFABETIZADO                                             35.0
                        ANALFABETO                                               22.5
                        ENSINO FUNDAMENTAL COMPLETO (8 ANOS ESTUDO)              46.6
                        ENSINO FUNDAMENTAL INCOMPLETO (8 ANOS ESTUDO)            25.2
                        ENSINO MEDIO COMPLETO (2º GRAU)                          37.0
                        ENSINO MEDIO INCOMPLETO ( 2º GRAU)                       36.9
                        ESCOLARIDADE - IGNORADA                                  32.4
                        OUTROS - ESCOLARIDADE                                    30.3
...                                                                               ...
SOLTEIRO                ENSINO MEDIO COMPLETO (2º GRAU)                          27.5
                        ENSINO MEDIO INCOMPLETO ( 2º GRAU)                       21.9
                        ESCOLARIDADE - IGNORADA                                  24.5
                        OUTROS - ESCOLARIDADE                                    21.1
                        POS-GRADUACAO                                            30.8
                        PREENCHIMENTO OPCIONAL                                   67.0
                        SUPERIOR COMPLETO                                        31.5
                        SUPERIOR INCOMPLETO                                      24.8
UNIAO ESTAVEL           ALFABETIZADO                                             35.6
                        ANALFABETO                                               45.3
                        ENSINO FUNDAMENTAL COMPLETO (8 ANOS ESTUDO)              31.9
                        ENSINO FUNDAMENTAL INCOMPLETO (8 ANOS ESTUDO)            34.8
                        ENSINO MEDIO COMPLETO (2º GRAU)                          31.7
                        ENSINO MEDIO INCOMPLETO ( 2º GRAU)                       31.2
                        ESCOLARIDADE - IGNORADA                                  32.9
                        OUTROS - ESCOLARIDADE                                    33.5
                        POS-GRADUACAO                                            42.5
                        SUPERIOR COMPLETO                                        36.4
                        SUPERIOR INCOMPLETO                                      33.4
VIUVO                   ALFABETIZADO                                             65.1
                        ANALFABETO                                               73.0
                        ENSINO FUNDAMENTAL COMPLETO (8 ANOS ESTUDO)              56.4
                        ENSINO FUNDAMENTAL INCOMPLETO (8 ANOS ESTUDO)            59.6
                        ENSINO MEDIO COMPLETO (2º GRAU)                          54.2
                        ENSINO MEDIO INCOMPLETO ( 2º GRAU)                       60.5
                        ESCOLARIDADE - IGNORADA                                  64.3
                        OUTROS - ESCOLARIDADE                                    63.0
                        POS-GRADUACAO                                            79.0
                        SUPERIOR COMPLETO                                        54.4
                        SUPERIOR INCOMPLETO                                      61.0

[90 rows x 1 columns]

In [8]:
colunas = ['Estado Civil', 'Idade Aparente']
df_envol[((df_envol['Idade Aparente']>=0)&
          (df_envol['Idade Aparente']<=1000))&
          (df_envol['Estado Civil'].isin(['CASADO', 'SOLTEIRO', 'VIUVO']))
        
        ][colunas].groupby(df_envol['Estado Civil']).mean().round(1)

KeyError: 'Idade Aparente'