In [2]:
import pandas as pd
import numpy as np
dir_crimes = r'I:\Meganz\PMMG\MySql\10 - Tbl_dimensao\gdo\tbl_base_GDO_2020.xls'#Home
#dir_crimes = r'C:\Users\Geo\Documents\MEGAsync\MySql\10 - Tbl_dimensao\gdo\tbl_base_GDO_2020.xls'#Office
df_crimes = pd.read_excel(dir_crimes, sheet_name='tbl_crimes')

In [21]:
import import_ipynb

import df_crimes

importing Jupyter notebook from df_crimes.ipynb
Empty DataFrame
Columns: [NREDS, LOGRADOURO, LOGRADOURO_NAO_CAD, LOGRADOURO_CRUZ, LOGRADOURO_CRUZ_NAO_CAD, N_LOG, BAIRRO, BAIRRO_NAO_CAD, COMPLEMENTO_END, PONTO_REF, MUNICIPIO, SETOR]
Index: []
Foram encontrados  Series([], Name: NREDS, dtype: int64) registros inválidos.

In [5]:
df = pd.read_sql_table('tbl_crimes', 'sqlite:///gdo.db', columns =['NREDS', 'DATA_FATO', 'CIA', 'UEOP', 'QTDE'])

In [64]:
df.filter(["NREDS", "CIA", "UEOP"])

                    NREDS             CIA            UEOP
0      2018-000013878-001  19ª CIA PM IND  19ª CIA PM IND
1      2018-000016724-001         51ª CIA         23º BPM
2      2018-000026381-001        241ª CIA         63º BPM
3      2018-000039155-001        241ª CIA         63º BPM
4      2018-000064030-001  19ª CIA PM IND  19ª CIA PM IND
...                   ...             ...             ...
50770  2019-041082317-001        241ª CIA         63º BPM
50771  2019-000780288-001        241ª CIA         63º BPM
50772  2019-038342449-001        241ª CIA         63º BPM
50773  2020-018864115-001        241ª CIA         63º BPM
50774  2018-047146395-001        142ª CIA         23º BPM

[50775 rows x 3 columns]

In [9]:
df.groupby(['UEOP'])['UEOP'].value_counts()

UEOP            UEOP
07º BPM         07º BPM           10715
19ª CIA PM IND  19ª CIA PM IND     5197
23º BPM         23º BPM           21070
60º BPM         60º BPM            7928
63º BPM         63º BPM            5865
Name: UEOP, dtype: int64

In [58]:
#df.pivot_table(index="CIA",columns="UEOP", margins =True, aggfunc="sum")

df.pivot_table(index='UEOP',columns=pd.Grouper(freq='M',key='DATA_FATO'), aggfunc=np.sum)

                     QTDE                                              \
DATA_FATO      2018-01-31 2018-02-28 2018-03-31 2018-04-30 2018-05-31
UEOP
07º BPM               488        391        422        360        416
19ª CIA PM IND        269        251        245        250        187
23º BPM               950        854        832        698        581
60º BPM               341        350        343        319        293
63º BPM               254        214        244        218        225

                                                                       ...  \
DATA_FATO      2018-06-30 2018-07-31 2018-08-31 2018-09-30 2018-10-31  ...
UEOP                                                                   ...
07º BPM               404        386        394        373        409  ...
19ª CIA PM IND        227        195        204        173        149  ...
23º BPM               808        759        792        746        742  ...
60º BPM               306        277        286        267        297  ...
63º BPM               253        222        244        199        247  ...

                                                                       \
DATA_FATO      2019-09-30 2019-10-31 2019-11-30 2019-12-31 2020-01-31
UEOP
07º BPM               285        316        382        386        359
19ª CIA PM IND        150        151        165        146        160
23º BPM               674        703        698        715        744
60º BPM               196        230        241        271        276
63º BPM               164        170        173        194        206


DATA_FATO      2020-02-29 2020-03-31 2020-04-30 2020-05-31 2020-06-30
UEOP
07º BPM               376        284        277        301        138
19ª CIA PM IND        118        125         80         86         55
23º BPM               724        625        530        458        211
60º BPM               255        225        237        216         93
63º BPM               209        145        142        134         81

[5 rows x 30 columns]

In [52]:
type(df['DATA_FATO'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [1]:
df_ad['DATA_FATO'].dt.month

df_ad[['DATA_FATO','DATA_FATO']]
df_ad['DATA_FATO'].dt.year
df_ad['NREDS'].count()

NameError: name 'df_ad' is not defined