In [6]:
import pandas as pd
import numpy as np
from datetime import datetime
df = pd.read_sql_table('tbl_envolvidos', 'sqlite:///gdo.db',
                       columns =['NREDS', 'COD_DIAO', 'T_C', 'COD_DELITO', 'T_C_DELITO',
                                 'DATA_FATO', 'CIA', 'UEOP', 'QTDE_ENVOL'])

In [10]:
df

,NREDS,COD_DIAO,T_C,COD_DELITO,T_C_DELITO,DATA_FATO,CIA,UEOP,QTDE_ENVOL
0,2018-057375780-002,C01157,CONSUMADO,C01157,CONSUMADO,2019-01-06,53ª CIA,23º BPM,1
1,2018-057375780-002,C01157,CONSUMADO,C01157,CONSUMADO,2019-01-06,53ª CIA,23º BPM,1
2,2018-057375780-002,C01157,CONSUMADO,C01180,CONSUMADO,2019-01-06,53ª CIA,23º BPM,1
3,2018-057375780-002,C01157,CONSUMADO,C01180,CONSUMADO,2019-01-06,53ª CIA,23º BPM,1
4,2018-057375780-002,C01157,CONSUMADO,C01180,CONSUMADO,2019-01-06,53ª CIA,23º BPM,1
...,...,...,...,...,...,...,...,...,...
12881,2020-029734540-001,C01157,CONSUMADO,C01157,CONSUMADO,2020-06-21,139ª CIA,23º BPM,1
12882,2020-029734540-001,C01157,CONSUMADO,C01157,CONSUMADO,2020-06-21,139ª CIA,23º BPM,1
12883,2020-029864738-001,C01157,CONSUMADO,C01157,CONSUMADO,2020-06-22,139ª CIA,23º BPM,1
12884,2020-029875688-001,C01157,CONSUMADO,C01157,CONSUMADO,2020-06-22,280ª CIA,60º BPM,1
12885,2020-029982294-001,C01157,CONSUMADO,C01157,CONSUMADO,2020-06-22,19ª CIA PM IND,19ª CIA PM IND,1

In [2]:
df.groupby(['UEOP'])['CIA'].value_counts()

UEOP            CIA
07º BPM         107ª CIA          1068
                118ª CIA           649
                50ª CIA            644
                141ª CIA           391
19ª CIA PM IND  19ª CIA PM IND    1020
23º BPM         142ª CIA          1913
                139ª CIA          1297
                51ª CIA           1019
                53ª CIA            661
60º BPM         279ª CIA          1624
                280ª CIA          1506
                other               10
63º BPM         290ª CIA           750
                241ª CIA           334
Name: CIA, dtype: int64

In [3]:
#df.query('AveragePrice <= 1')
#df.query('type != "conventional"')
df.query('UEOP == "23º BPM" & CIA  in["53ª CIA", "142ª CIA"]', inplace = True)
df.groupby(['UEOP'])['CIA'].value_counts()

UEOP     CIA
23º BPM  142ª CIA    1913
         53ª CIA      661
Name: CIA, dtype: int64

In [46]:
df.count()

NREDS        11214
COD_DIAO     11214
DATA_FATO    11214
CIA          11214
UEOP         11214
QTDE         11214
dtype: int64

In [4]:
start_date = '2020-01-01'
end_date = '2020-12-31'
df.query('COD_DIAO == "B01121" & T_C == "CONSUMADO" | COD_DELITO in ["B01121"] & T_C_DELITO == "CONSUMADO"',
         inplace = True)
df

,NREDS,COD_DIAO,T_C,COD_DELITO,T_C_DELITO,DATA_FATO,CIA,UEOP,QTDE_ENVOL
67,2019-000426766-001,B01121,CONSUMADO,B01121,CONSUMADO,2019-01-03,142ª CIA,23º BPM,1
68,2019-000426766-001,B01121,CONSUMADO,B01121,CONSUMADO,2019-01-03,142ª CIA,23º BPM,1
69,2019-000426766-001,B01121,CONSUMADO,B01121,CONSUMADO,2019-01-03,142ª CIA,23º BPM,1
101,2019-000677394-001,B01121,CONSUMADO,B01121,CONSUMADO,2019-01-05,53ª CIA,23º BPM,1
102,2019-000677394-001,B01121,CONSUMADO,B01121,CONSUMADO,2019-01-05,53ª CIA,23º BPM,1
...,...,...,...,...,...,...,...,...,...
12663,2020-027257432-003,B01121,CONSUMADO,B01121,CONSUMADO,2020-06-08,142ª CIA,23º BPM,1
12664,2020-027257432-003,B01121,CONSUMADO,B01121,CONSUMADO,2020-06-08,142ª CIA,23º BPM,1
12665,2020-027257432-003,B01121,CONSUMADO,B01121,CONSUMADO,2020-06-08,142ª CIA,23º BPM,1
12666,2020-027257432-003,B01121,CONSUMADO,B01121,CONSUMADO,2020-06-08,142ª CIA,23º BPM,1
12667,2020-027257432-003,B01121,CONSUMADO,B01121,CONSUMADO,2020-06-08,142ª CIA,23º BPM,1

In [5]:
start_date = '2020-01-01'
pd.to_datetime(start_date, format='%d/%m/%Y', errors = 'coerce').dt.date
end_date = '2020-12-31'
df.query(['DATA_FATO'] == start_date,  inplace = True)
#df.query(['DATA_FATO'] > start_date & ['DATA_FATO'] <= end_date, inplace = True)
df

AttributeError: 'NaTType' object has no attribute 'dt'

In [109]:
df['DATA_FATO'] = pd.to_datetime(df['DATA_FATO'], format='%d/%m/%Y', errors = 'coerce').dt.date
#df['DATA_FATO']

In [119]:
start_date = '2020-01-01'
pd.to_datetime('2020-01-01', format='%Y-%m-%d', errors = 'coerce').dt.date

AttributeError: 'Timestamp' object has no attribute 'dt'

In [137]:
#df['DATA_FATO']=pd.to_datetime(df['DATA_FATO'], format='%Y-%m-%d')

date_init = '2020-01-01' # Infome da  data inicial da pesquisa
date_end = '2020-12-31' # Infome da  data final da pesquisa

datetime.strptime(date_init, '%Y-%m-%d')

datetime.strptime(date_end, '%Y-%m-%d')

df = df.loc[(df['DATA_FATO']>=date_init) & (df['DATA_FATO']<date_end)]

In [138]:
df

,NREDS,COD_DIAO,T_C,COD_DELITO,T_C_DELITO,DATA_FATO,CIA,UEOP,QTDE_ENVOL
9376,2020-000133938-001,C01157,CONSUMADO,C01157,CONSUMADO,2020-01-02,280ª CIA,60º BPM,1
9377,2020-000133938-001,C01157,CONSUMADO,C01157,CONSUMADO,2020-01-02,280ª CIA,60º BPM,1
9378,2020-000133938-001,C01157,CONSUMADO,C01157,CONSUMADO,2020-01-02,280ª CIA,60º BPM,1
9391,2020-000220318-001,C01157,CONSUMADO,C01157,CONSUMADO,2020-01-02,279ª CIA,60º BPM,1
9392,2020-000220318-001,C01157,CONSUMADO,C01157,CONSUMADO,2020-01-02,279ª CIA,60º BPM,1
...,...,...,...,...,...,...,...,...,...
12828,2020-029187844-001,B01121,TENTADO,B01121,TENTADO,2020-06-18,107ª CIA,07º BPM,1
12829,2020-029187844-001,B01121,TENTADO,B01121,TENTADO,2020-06-18,107ª CIA,07º BPM,1
12830,2020-029237386-001,C01157,CONSUMADO,C01155,CONSUMADO,2020-06-18,51ª CIA,23º BPM,1
12831,2020-029237386-001,C01157,CONSUMADO,C01155,CONSUMADO,2020-06-18,51ª CIA,23º BPM,1
12832,2020-029240076-001,C01157,CONSUMADO,C01157,CONSUMADO,2020-06-18,51ª CIA,23º BPM,1